spring.datasource.url=jdbc:postgresql://localhost:5432/votum
spring.datasource.username=postgres
spring.datasource.password=zandubalm30

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

file.storage.path=secure_storage

jwt.secret=SuperSecretKeyForEVotingSystem123456
jwt.expiration=86400000